### ISSUE TITLE
Problem with npm run dev

### ISSUE THREAD

**Issue by cgmerida** [hafeez1042/Adminator-HTML5-Admin-Template-Laravel-Implementation#3] opened 2018-10-07 23:05 UTC
I have an error when I run npm run dev. i copy just a part of the error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2

**Comment by edtorba** [comment] 2018-10-19 20:47
@cgmerida That's because one of the scss files tried to import non-existing file. If you navigate to `resources - assets - sass - admin - index.scss` and comment out `@import vendor/index` or create that folder, it will compile.

**Comment by edtorba** [comment] 2018-10-19 21:32
Ignore my message above, dupe of #1

**Closed** 2018-10-29 20:40 UTC
